version: 2
registries:
  npm-public:
    type: npm-registry
    url: https://registry.npmjs.org
    replaces-base: true

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    registries:
      - npm-public
